### ISSUE TITLE
Alt Tab not working properly

### ISSUE THREAD

**Issue by netfun81** [orellazri/mswm#2]
Nice start on this window manager.  You may already know, but the Alt-Tab function is not cycling through all open applications. It will sometimes lower one application but then have no effect when pressing again on the next open application.   If I raise an application with Alt-left mouse button, the Alt-Tab seems to lower it again but not cycle back to it without raising it again with.  Looking forward to future improvements.

**Comment by orellazri** [comment]
Hi, thanks for leaving feedback!
This issue is now solved, since I switched the logic of workspaces to be a two-dimensional vector instead of an hash map, and now switching windows based on the active window (and not the event's window/subwindow), and only in the active workspace.

See commit https://github.com/orellazri/mswm/commit/55f0214e00b0e7a1067de7dc0b3a06f2e8bfb0f5
